### ISSUE TITLE
Format

### ISSUE THREAD

**Issue by edgartdata** [PHAROS-photoarchives/Zeri-Foundation#1]
Line 18: what is OGTS[@etichetta='Format'] "album, carpet, merging of photos"?

**Comment by marilenadaquino** [comment]
Is the type of object being catalogued. Used when collections of photos are catalogued instead (or along with) of the single photographs.

**Comment by edgartdata** [comment]
I understand album, and maybe even collage but you lost me at carpet :)

**Comment by marilenadaquino** [comment]
ahahah now I noticed that. I guess it is supposed to be folder
