### ISSUE TITLE
Identifiers of the entry describing the work of art depicted in the photo

### ISSUE THREAD

**Issue by edgartdata** [PHAROS-photoarchives/Zeri-Foundation#12]
I have deleted this row taht was in teh Artwork Identification section:
DO NOT ENTER DATA IN THIS ROW-Identifiers of the entry describing the work of art depicted in the photo |   |   |   |   |   | SERCD[@etichetta="SERCD"]    NCTN[@etichetta="Id. number"] | 1654015638 |

If you need it, please, map it appropriately in the doc https://docs.google.com/spreadsheets/d/1QdgGkS2QjI1WewerrReNoVddCh3IK9Zi6hU11xzdNZE/edit#gid=2141014877

**Comment by marilenadaquino** [comment]
ok!
